### ISSUE TITLE
examples for new yaml structure

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/schemas#17]
**OpenMP example using gnu and intel**

Description: This test should compile *hello.c* with gnu and intel compiler using ``OMP_NUM_THREADS=2``

```
source: hello.c
scheduler: local
compile: yes
matrix: 
  env:
    - OMP_NUM_THREADS=2
  compilers:
   - gnu
   - intel
  cflags:
    gnu:
      - "-O2 -fopenmp"
    intel:
      - "-O2 -fopenmp"

pre_build:
  - echo "pre build commands"
  - time

post_build:
  - echo "post build command"
  - time  
```

**Multiple Compilation Flags with gnu and intel compiler**
Description: hello.c will be compiled with gnu and intel compiler with two combination for cflags for gnu and intel totaling 4 compilations
```
source: hello.c
compile: yes
matrix:
  compiler:
    - gnu
    - intel
  cflags:
    gnu:
      - "-O2 --fast"
      - "-O3"
   intel:
     - "-O2 --fma"
     - "-O1 -g"
```

**Test without a build**
Description: This test is just running shell commands without any compilation
```
compile: no
pre_run:
  - time
run:
  - mpirun -np 2 osu_gather
post_run:
  - time
```
